packages:
  - '.'

overrides:
  '@mastra/ai-sdk': link:../../../client-sdks/ai-sdk
  '@mastra/client-js': link:../../../client-sdks/client-js
  '@mastra/core': link:../../core
  '@mastra/memory': link:../../memory
  '@mastra/fastembed': link:../../fastembed
  '@mastra/libsql': link:../../../stores/libsql
  '@mastra/pg': link:../../../stores/pg
  '@mastra/upstash': link:../../../stores/upstash
  mastra: link:../../cli
  '@internal/llm-recorder': link:../../_llm-recorder
  '@internal/test-utils': link:../../_test-utils
  '@internal/ai-v6': link:../../_vendored/ai_v6
  '@mastra/schema-compat': link:../../schema-compat

allowBuilds:
  esbuild: false
  sharp: false
