# This file makes agent-hub a standalone workspace
packages:
  - .

overrides:
  '@mastra/core': link:../../../../packages/core
  '@mastra/libsql': link:../../../../stores/libsql
  '@mastra/observability': link:../../../mastra
  '@mastra/otel-bridge': link:../../../otel-bridge
  '@mastra/server': link:../../../../packages/server
  systeminformation: 5.31.0
  ajv@<=8.18.0: 8.18.0
  fast-uri@<3.1.5: 3.1.5
  minimatch@<=10.2.1: 10.2.1
  '@isaacs/brace-expansion@<=5.0.1': 5.0.1
