/**
 * Bug 3 regression test: when a durable agent runs with a Mastra-managed
 * background-task manager and a background-eligible tool, the system prompt
 * sent to the model must include the background-task guidance generated by
 * `generateBackgroundTaskSystemPrompt`. Previously the durable workflow
 * skipped this injection point entirely.
 */
import type { LanguageModelV2 } from '@ai-sdk/provider-v5';
import { MockLanguageModelV2, convertArrayToReadableStream } from '@internal/ai-sdk-v5/test';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { z } from 'zod';
import { EventEmitterPubSub } from '../../../events/event-emitter';
import { Mastra } from '../../../mastra';
import { MockStore } from '../../../storage/mock';
import { createTool } from '../../../tools';
import { Agent } from '../../agent';
import { createDurableAgent } from '../create-durable-agent';

describe('Bug 3: background-task system prompt on durable', () => {
  let pubsub: EventEmitterPubSub;
  const storage = new MockStore();

  beforeEach(() => {
    pubsub = new EventEmitterPubSub();
  });

  afterEach(async () => {
    await pubsub.close();
    const bgStore = await storage.getStore('backgroundTasks');
    await bgStore?.dangerouslyClearAll();
  });

  it('injects the background-task guidance into the leading system message', async () => {
    const promptSnapshots: Array<{ role: string; content: any }[]> = [];
    let resolveCalled: () => void;
    const calledPromise = new Promise<void>(r => {
      resolveCalled = r;
    });
    const mockModel = new MockLanguageModelV2({
      doStream: async ({ prompt }) => {
        promptSnapshots.push(prompt as any);
        resolveCalled();
        return {
          rawCall: { rawPrompt: null, rawSettings: {} },
          warnings: [],
          stream: convertArrayToReadableStream([
            { type: 'stream-start', warnings: [] },
            { type: 'response-metadata', id: 'id-0', modelId: 'mock', timestamp: new Date(0) },
            { type: 'text-start', id: 't' },
            { type: 'text-delta', id: 't', delta: 'ok' },
            { type: 'text-end', id: 't' },
            {
              type: 'finish',
              finishReason: 'stop',
              usage: { inputTokens: 1, outputTokens: 1, totalTokens: 2 },
            },
          ]),
        };
      },
    });

    const researchTool = createTool({
      id: 'research',
      description: 'Research a topic',
      inputSchema: z.object({ topic: z.string() }),
      execute: async () => ({ summary: 'noop' }),
      background: { enabled: true },
    });

    const baseAgent = new Agent({
      id: 'bg-prompt-agent',
      name: 'BG Prompt Agent',
      instructions: 'Research topics when asked',
      model: mockModel as LanguageModelV2,
      tools: { research: researchTool },
      backgroundTasks: { tools: { research: true } },
    });

    const durableAgent = createDurableAgent({ agent: baseAgent, pubsub });
    new Mastra({
      logger: false,
      storage,
      backgroundTasks: { enabled: true },
      agents: { 'bg-prompt-agent': durableAgent as any },
    });

    const { cleanup } = await durableAgent.stream('hi', { onChunk: () => {} });
    await calledPromise;
    cleanup();

    expect(promptSnapshots.length).toBeGreaterThan(0);
    const firstPrompt = promptSnapshots[0]!;
    const systemMessage = firstPrompt.find(m => m.role === 'system');
    expect(systemMessage).toBeDefined();
    const systemContent = typeof systemMessage!.content === 'string' ? systemMessage!.content : '';
    expect(systemContent).toContain('Research topics when asked');
    // The background-task prompt always mentions the `_background` field and
    // lists each eligible tool by name.
    expect(systemContent).toContain('_background');
    expect(systemContent).toContain('research');
  });

  it('skips the injection when no background-task manager is wired in', async () => {
    const promptSnapshots: Array<{ role: string; content: any }[]> = [];
    let resolveCalled: () => void;
    const calledPromise = new Promise<void>(r => {
      resolveCalled = r;
    });
    const mockModel = new MockLanguageModelV2({
      doStream: async ({ prompt }) => {
        promptSnapshots.push(prompt as any);
        resolveCalled();
        return {
          rawCall: { rawPrompt: null, rawSettings: {} },
          warnings: [],
          stream: convertArrayToReadableStream([
            { type: 'stream-start', warnings: [] },
            { type: 'response-metadata', id: 'id-0', modelId: 'mock', timestamp: new Date(0) },
            { type: 'text-start', id: 't' },
            { type: 'text-delta', id: 't', delta: 'ok' },
            { type: 'text-end', id: 't' },
            {
              type: 'finish',
              finishReason: 'stop',
              usage: { inputTokens: 1, outputTokens: 1, totalTokens: 2 },
            },
          ]),
        };
      },
    });

    const greetTool = createTool({
      id: 'greet',
      description: 'Greet a person',
      inputSchema: z.object({ name: z.string() }),
      execute: async ({ name }) => `Hello, ${name}!`,
    });

    const baseAgent = new Agent({
      id: 'no-bg-agent',
      name: 'No BG Agent',
      instructions: 'Greet people',
      model: mockModel as LanguageModelV2,
      tools: { greet: greetTool },
    });

    const durableAgent = createDurableAgent({ agent: baseAgent, pubsub });
    new Mastra({
      logger: false,
      storage,
      agents: { 'no-bg-agent': durableAgent as any },
    });

    const { cleanup } = await durableAgent.stream('hi', { onChunk: () => {} });
    await calledPromise;
    cleanup();

    expect(promptSnapshots.length).toBeGreaterThan(0);
    const systemMessage = promptSnapshots[0]!.find(m => m.role === 'system');
    const systemContent = typeof systemMessage!.content === 'string' ? systemMessage!.content : '';
    expect(systemContent).toContain('Greet people');
    expect(systemContent).not.toContain('_background');
  });
});
