name: Workspace Tests

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      head_sha:
        required: true
        type: string
      workspace_packages:
        required: true
        type: string
      workspace_docker_packages:
        required: true
        type: string
    secrets:
      TURBO_TOKEN:
        required: false
      TURBO_TEAM:
        required: false

jobs:
  test-unit:
    if: ${{ github.repository == 'mastra-ai/mastra' && inputs.workspace_packages != '[]' }}
    runs-on: starsling-ubuntu-24.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_CACHE: remote:r
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(inputs.workspace_packages) }}
    steps:
      - uses: actions/checkout@e8d4307400f9427dba7cb98e488d6ab85f1cec5f
        timeout-minutes: 20
        with:
          ref: ${{ inputs.head_sha }}
          persist-credentials: false

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-node

      - name: Build packages
        run: pnpm turbo build --filter "@mastra/${{ matrix.package }}"

      - name: Run ${{ matrix.package }} unit tests
        run: pnpm test:unit
        working-directory: workspaces/${{ matrix.package }}
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'

  test-docker:
    if: ${{ github.repository == 'mastra-ai/mastra' && inputs.workspace_docker_packages != '[]' }}
    runs-on: starsling-ubuntu-24.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_CACHE: remote:r
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(inputs.workspace_docker_packages) }}
    steps:
      - uses: actions/checkout@e8d4307400f9427dba7cb98e488d6ab85f1cec5f
        timeout-minutes: 20
        with:
          ref: ${{ inputs.head_sha }}
          persist-credentials: false

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-node

      - name: Build packages
        run: pnpm turbo build --filter "@mastra/${{ matrix.package }}"

      - name: Run ${{ matrix.package }} integration tests
        run: pnpm test
        working-directory: workspaces/${{ matrix.package }}
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
